-- V3__seed_chalets.sql
-- Seed de chalets de démo (étendu)

INSERT INTO chalets (name, location, price_per_night) VALUES
-- (liste d’origine)
('Mont-Tremblant Cozy',        'Laurentides, QC',              180.00),
('Lac Beauport View',          'Québec, QC',                   220.00),
('Charlevoix Vista',           'Charlevoix, QC',               260.00),
('Blue Mountains Retreat',     'Ontario, ON',                  200.00),
('Banff Pine Lodge',           'Alberta, AB',                  300.00),
('Whistler Peak Cabin',        'British Columbia, BC',         320.00),
('Estrie Serenity',            'Estrie, QC',                   150.00),
('Gaspésie Sea Breeze',        'Gaspésie, QC',                 170.00),
('Saguenay Fjord',             'Saguenay–Lac-Saint-Jean, QC',  210.00),
('Outaouais Forest Home',      'Outaouais, QC',                190.00),
('La Malbaie Riverside',       'Charlevoix, QC',               245.00),
('Saint-Donat Lakehouse',      'Lanaudière, QC',               195.00),
('Magog Lakefront',            'Estrie, QC',                   205.00),
('Bromont Hillside',           'Estrie, QC',                   180.00),
('Mont-Orford Pines',          'Estrie, QC',                   190.00),
('Rawdon Rapids Chalet',       'Lanaudière, QC',               165.00),
('Sutton Creek Cabin',         'Estrie, QC',                   175.00),
('Mont-Laurier Hideaway',      'Laurentides, QC',              160.00),
('Montebello Heritage',        'Outaouais, QC',                200.00),
('Saint-Sauveur Loft',         'Laurentides, QC',              170.00),
('Baie-Saint-Paul Maple',      'Charlevoix, QC',               230.00),
('Matane Dunes',               'Bas-Saint-Laurent, QC',        150.00),
('Rimouski Shoreline',         'Bas-Saint-Laurent, QC',        155.00),
('Percé Cliff House',          'Gaspésie, QC',                 185.00),
('Tadoussac Beluga View',      'Côte-Nord, QC',                210.00),
('Chicoutimi Overlook',        'Saguenay–Lac-Saint-Jean, QC',  200.00),
('Val-d''Or Boreal',           'Abitibi-Témiscamingue, QC',    160.00),
('Rouyn-Noranda Retreat',      'Abitibi-Témiscamingue, QC',    165.00),
('Lac-Mégantic Sunrise',       'Estrie, QC',                   170.00),
('Shawinigan Riverside',       'Mauricie, QC',                 160.00),
('La Tuque Timber',            'Mauricie, QC',                 155.00),
('Joliette Riverbend',         'Lanaudière, QC',               150.00),
('Ste-Adèle Woodland',         'Laurentides, QC',              165.00),
('Lévis Panorama',             'Chaudière-Appalaches, QC',     170.00),
('Quebec City Stonehouse',     'Québec, QC',                   195.00),
('Îles-de-la-Madeleine Breeze','Îles-de-la-Madeleine, QC',     205.00),
('Canmore Ridge Chalet',       'Alberta, AB',                  275.00),
('Jasper Lakeside',            'Alberta, AB',                  290.00),
('Kelowna Vineyard Cabin',     'British Columbia, BC',         285.00),
('Tofino Surf Cabin',          'British Columbia, BC',         320.00);
