spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chalethub
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
  application:
    name: chalet-hub-backend
logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.jdbc.core: DEBUG
server:
  port: 8080
